import Nav from "@/components/Nav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className=" mx-auto min-h-screen flex flex-col">
     

{/* <Nav></Nav> */}
<main className=" mx-auto flex-grow flex justify-center items-center  overflow-auto">
      
        {children}
        </main>
       
        </body>
   
   
    </html>
  );
}
