import Nav from "@/components/Nav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className="w mx-auto min-h-screen flex flex-col">
        
<Nav></Nav>
<main className="container mx-auto flex-grow flex justify-center items-center mt-16 overflow-auto">
      
        {children}
        </main>
        </body>
   
   
    </html>
  );
}
